package psp.models.species;

import com.fasterxml.jackson.annotation.*;
import java.util.List;

@lombok.Data
public class Species {
    @lombok.Getter(onMethod_ = {@JsonProperty("base_happiness")})
    @lombok.Setter(onMethod_ = {@JsonProperty("base_happiness")})
    private long baseHappiness;
    @lombok.Getter(onMethod_ = {@JsonProperty("capture_rate")})
    @lombok.Setter(onMethod_ = {@JsonProperty("capture_rate")})
    private long captureRate;
    @lombok.Getter(onMethod_ = {@JsonProperty("color")})
    @lombok.Setter(onMethod_ = {@JsonProperty("color")})
    private Color color;
    @lombok.Getter(onMethod_ = {@JsonProperty("egg_groups")})
    @lombok.Setter(onMethod_ = {@JsonProperty("egg_groups")})
    private List<Color> eggGroups;
    @lombok.Getter(onMethod_ = {@JsonProperty("evolution_chain")})
    @lombok.Setter(onMethod_ = {@JsonProperty("evolution_chain")})
    private SpeciesEvolutionChain evolutionChain;
    @lombok.Getter(onMethod_ = {@JsonProperty("evolves_from_species")})
    @lombok.Setter(onMethod_ = {@JsonProperty("evolves_from_species")})
    private Object evolvesFromSpecies;
    @lombok.Getter(onMethod_ = {@JsonProperty("flavor_text_entries")})
    @lombok.Setter(onMethod_ = {@JsonProperty("flavor_text_entries")})
    private List<SpeciesFlavorTextEntry> flavorTextEntries;
    @lombok.Getter(onMethod_ = {@JsonProperty("form_descriptions")})
    @lombok.Setter(onMethod_ = {@JsonProperty("form_descriptions")})
    private List<Object> formDescriptions;
    @lombok.Getter(onMethod_ = {@JsonProperty("forms_switchable")})
    @lombok.Setter(onMethod_ = {@JsonProperty("forms_switchable")})
    private boolean formsSwitchable;
    @lombok.Getter(onMethod_ = {@JsonProperty("gender_rate")})
    @lombok.Setter(onMethod_ = {@JsonProperty("gender_rate")})
    private long genderRate;
    @lombok.Getter(onMethod_ = {@JsonProperty("genera")})
    @lombok.Setter(onMethod_ = {@JsonProperty("genera")})
    private List<Genus> genera;
    @lombok.Getter(onMethod_ = {@JsonProperty("generation")})
    @lombok.Setter(onMethod_ = {@JsonProperty("generation")})
    private Color generation;
    @lombok.Getter(onMethod_ = {@JsonProperty("growth_rate")})
    @lombok.Setter(onMethod_ = {@JsonProperty("growth_rate")})
    private Color growthRate;
    @lombok.Getter(onMethod_ = {@JsonProperty("habitat")})
    @lombok.Setter(onMethod_ = {@JsonProperty("habitat")})
    private Color habitat;
    @lombok.Getter(onMethod_ = {@JsonProperty("has_gender_differences")})
    @lombok.Setter(onMethod_ = {@JsonProperty("has_gender_differences")})
    private boolean hasGenderDifferences;
    @lombok.Getter(onMethod_ = {@JsonProperty("hatch_counter")})
    @lombok.Setter(onMethod_ = {@JsonProperty("hatch_counter")})
    private long hatchCounter;
    @lombok.Getter(onMethod_ = {@JsonProperty("id")})
    @lombok.Setter(onMethod_ = {@JsonProperty("id")})
    private long id;
    @lombok.Getter(onMethod_ = {@JsonProperty("is_baby")})
    @lombok.Setter(onMethod_ = {@JsonProperty("is_baby")})
    private boolean isBaby;
    @lombok.Getter(onMethod_ = {@JsonProperty("is_legendary")})
    @lombok.Setter(onMethod_ = {@JsonProperty("is_legendary")})
    private boolean isLegendary;
    @lombok.Getter(onMethod_ = {@JsonProperty("is_mythical")})
    @lombok.Setter(onMethod_ = {@JsonProperty("is_mythical")})
    private boolean isMythical;
    @lombok.Getter(onMethod_ = {@JsonProperty("name")})
    @lombok.Setter(onMethod_ = {@JsonProperty("name")})
    private String name;
    @lombok.Getter(onMethod_ = {@JsonProperty("names")})
    @lombok.Setter(onMethod_ = {@JsonProperty("names")})
    private List<Name> names;
    @lombok.Getter(onMethod_ = {@JsonProperty("order")})
    @lombok.Setter(onMethod_ = {@JsonProperty("order")})
    private long order;
    @lombok.Getter(onMethod_ = {@JsonProperty("pal_park_encounters")})
    @lombok.Setter(onMethod_ = {@JsonProperty("pal_park_encounters")})
    private List<PalParkEncounter> palParkEncounters;
    @lombok.Getter(onMethod_ = {@JsonProperty("pokedex_numbers")})
    @lombok.Setter(onMethod_ = {@JsonProperty("pokedex_numbers")})
    private List<PokedexNumber> pokedexNumbers;
    @lombok.Getter(onMethod_ = {@JsonProperty("shape")})
    @lombok.Setter(onMethod_ = {@JsonProperty("shape")})
    private Color shape;
    @lombok.Getter(onMethod_ = {@JsonProperty("varieties")})
    @lombok.Setter(onMethod_ = {@JsonProperty("varieties")})
    private List<Variety> varieties;
}
